### PR TITLE
Refactored Yom HaShoah conditions

### PR DESCRIPTION
**Pull request by catalandres**
...now they are a tad simpler and follow the scheduling logic :)

### CODE REVIEW

**Comment by KosherJava** [comment]
Does this PR request supersede the previous one? or are both PRs required?

**Comment by catalandres** [comment]
They affect different lines (220 and 221). They are independent, as far as I remember.

**Comment by catalandres** [comment]
Confirmed: they affect different conditions of when it is Yom haShoah.

**Comment by KosherJava** [comment]
@catalandres , can you resolve the merge conflict on this one?

**Comment by catalandres** [comment]
I cannot do the merge — I don't have write access. Can you help with that?

From what I can see this PR is pretty simple — just one line changes and a CR is added at the end of the file. Do you know if syncing my fork with the current state of `master` and resubmitting the PR would help in any way?

**Comment by dakom** [comment]
I'm working off a port of the same codebase and don't have java setup for running tests - I believe this update fails for 5777...

**Comment by dakom** [comment]
changed from `(dayOfMonth == 28 && dayOfWeek == 1)` to `(dayOfMonth == 28 && dayOfWeek == 2)` for now

**Pull request merged**
